### Get all books
GET http://localhost:8080/books
Accept: application/json

### Add a new book
POST http://localhost:8080/books
Content-Type: application/json

{
  "title": "The Antichrist",
  "author": "Friedrich Nietzsche",
  "genre": "Philosophy"
}

### Get a book by ID
GET http://localhost:8080/books/1
Accept: application/json

### Update a book by ID
PUT http://localhost:8080/books/1
Content-Type: application/json

{
  "title": "Thus Spoke Zarathustra",
  "author": "Friedrich Nietzsche",
  "genre": "Philosophy"
}

### Delete a book by ID
DELETE http://localhost:8080/books/2
